# Site settings
title: Naoko P Kurata
email: nkurata@amnh.org
url: https://kuratanp.github.io

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Naoko P Kurata

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  
  - title: twitter
    url: https://twitter.com/KurataPN
  - title: youtube
    url: https://www.youtube.com/watch?v=Lpsu7luhHA4
  - title: linkedin
    url: https://www.linkedin.com/in/naoko-p-kurata-a9837093/


# Build settings
markdown: kramdown
permalink: pretty
